name: Deploy Three-Tier AWS Infra

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    name: Terraform Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Debug - Check Directory Existence
        run: ls -la

      - name: Ensure Terraform Directory Exists
        run: mkdir -p ./three-tier-arch

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Ensure Scripts Are Executable
        run: chmod +x *.sh || true
        working-directory: ./three-tier-arch

      - name: Initialize Terraform
        run: terraform init
        working-directory: ./three-tier-arch

      - name: Validate Terraform
        run: terraform validate
        working-directory: ./three-tier-arch

      - name: Plan Terraform
        run: terraform plan -out=tfplan
        working-directory: ./three-tier-arch

      - name: Show Terraform Plan
        run: terraform show -json tfplan | jq .
        working-directory: ./three-tier-arch

      - name: Apply Terraform
        run: terraform apply -auto-approve
        working-directory: ./three-tier-arch

      - name: Destroy Terraform (Optional)
        if: ${{ github.event_name == 'pull_request' }}  # Only run on PRs
        run: terraform destroy -auto-approve
        working-directory: ./three-tier-arch
